name: SimpleMedic
version: 1.1
description: A Minecraft, professional medic at your aide.
author: never2nv
main: me.never2nv.SimpleMedic.SimpleMedic
commands:
     medic:
              description: Need a medic? Request one now!
     med:
              description: Need a medic? Request one now!
     burn:
              description: Burn those players!
              permission: simplemedic.burn
     extme:
              description: Extinguishes the fire that is burning you!
     extinguishme:
              description: Extinguishes the fire that is burning you!

permissions:
  simplemedic.*:
    description: Gives access to all Medic commands
    children:
      simplemedic.heal: true
  simplemedic.heal:
    description: Allows you request a medic to heal yourself.
    default: op
  simplemedic.heal.others:
    description: Allows you request a medic to heal another player.
    default: op
  simplemedic.burn:
    description: Allows you to set someone on fire or yourself.
    default: op
  simplemedic.ext:
    description: Allows you to use /extme.
    default: op
  simplemedic.ext.others:
    description: Allows you to use /extme on another player
    default: op